[project]
name = "producer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.11",
    "praw>=7.8.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
